[package]
name = "cracking-the-coding-interview-with-rust"
version = "0.1.0"
authors = ["yingyangcode <marcel.anis.21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
